Repository shyamal31/units_converter_extension, pull requests merged in 2023-11, with the labels that each got.

#6 Enhancements
  code/conversions/Area.js
  code/conversions/Data.js
  code/conversions/DataTransfer.js
  code/conversions/Length.js
  code/conversions/Mass.js
  code/conversions/Speed.js
  code/conversions/Time.js
  code/conversions/Volume.js
  code/conversions/conversion.js
  code/main_scripts/custom_units.js
  code/main_scripts/parser_script.js
  code/main_scripts/popular_units.js
  code/main_scripts/units_objects.js
  code/main_scripts/utility.js
  manifest.json
Labels: enhancement

#10 User input box
  code/conversions/conversion.js
  code/popup/js/jquery/jquery-3.7.1.min.js
  code/popup/js/popup.js
  code/popup/popup.css
  code/popup/popup.html
  manifest.json
Labels: enhancement

#11 Favourite tab updated
  code/conversions/Currency.js
  code/main_scripts/content_script.js
  code/main_scripts/custom_units.js
  code/popup/js/popup.js
  code/popup/popup.css
  code/popup/popup.html
Labels: bug

#12 pop up css improved
  code/popup/popup.css
  code/styling/content_script.css
Labels: bug

#15 Custom Unit Delete Feature Implemented
  code/main_scripts/custom_units.js
  code/popup/js/popup.js
  code/popup/popup.css
  code/popup/popup.html
Labels: enhancement

#18 Fav Currency Bug Fixed
  code/popup/js/popup.js
Labels: bug

#17 Shail611 patch 1
  README.md
Labels: documentation

#14 Add timezone conversion
  code/conversions/TimeZone.js
  code/conversions/conversion.js
  code/main_scripts/content_script.js
  code/main_scripts/custom_units.js
  code/main_scripts/parser_script.js
  docs/Speed.js.html
  manifest.json
  package-lock.json
  package.json
  test/Area_test.js
  test/DataTransfer_test.js
  test/Data_test.js
  test/Length_test.js
  test/Mass_test.js
  test/Speed_test.js
  test/TimeZone_test.js
  test/Time_test.js
  test/Volume_test.js
Labels: enhancement

#19 Update Documentation
  docs/custom_units.md
  docs/test_doc/conversion_test.md
  docs/test_doc/currency_test.md
  docs/test_doc/temperature_test.md
  docs/test_doc/test.md
  docs/test_doc/timezone_test.md
  docs/timezone.md
Labels: documentation

#25 Update currency_test.md
  docs/test_doc/currency_test.md
  docs/test_doc/temperature_test.md
Labels: documentation

#24 Update README.md
  README.md
Labels: documentation

#21 Update README.md
  README.md
Labels: documentation
